name = "moq-docs"
compatibility_date = "2025-12-13"

pages_build_output_dir = ".vitepress/dist"

# Deployment is done via `wrangler pages deploy`
# Example: wrangler pages deploy .vitepress/dist --project-name=moq-docs
